### PR TITLE
Major bug fix against XSS in username

### PR DESCRIPTION
**Pull request by joker314**
This will be the error rovided if an nvalid username is entered during registration, usernames must match:
/^[0-9A-Za-z_]+$/
to be allowed

### CODE REVIEW

**Comment by bjskistad** [comment]
Looks good to me. :+1:

**Comment by joker314** [comment]
Merge (both?)

**Comment by bjskistad** [comment]
Sure.

**Comment by joker314** [comment]
I was told I'm not supposed to merge my own code, but if you approve then am I allowed to do it myself?

**Comment by bjskistad** [comment]
Yeah.

**Pull request merged**
