### PR TITLE
Add space in ternary operator

### PR DESCRIPTION
**Pull request by jeandrek**
I think this looks more readable.

### CODE REVIEW

**Comment by jeandrek** [comment]
Should I merge??

**Comment by robinp7720** [comment]
Yes, just make sure not to overwrite my changes :p

**Comment by jeandrek** [comment]
No. git is smart and detects stuff like that and doesn't allow it

**Comment by adri326** [comment]
Hey, robinp, do you give us (Newawe) an MySQL DB?

**Comment by robinp7720** [comment]
@adri326 Yes, I can easily create a MySQL user for this. The details will be hidden though. You have  setup your own MySQL server for debugging

**Pull request merged**
