### PR TITLE
added a function to escape HTML tags

### PR DESCRIPTION
**Pull request by joker314**
*WARNING* The function is there, but it needs to be executed somewhere, and I have not done that (yet?).

### CODE REVIEW

**Comment by bjskistad** [comment]
We don't want to replace the chars that are invalid, we want to give an error and not register them.

**Comment by joker314** [comment]
But the function can be used in comments, and stuff. Surely a user should be allowed to type:
5 is < 6
without getting an error? And I only added the function, and have not executed it anywhere. But I think it would get us 1 step closer to fighting against XSS (and SQL injection, if we ever get a database)

**Comment by joker314** [comment]
May I merge (no response = merge at 1800 UTC)

**Comment by bjskistad** [comment]
Yes, they will be able to comment those characters... I thought you meant this for registration.

**Pull request merged**
