### PR TITLE
Create new TOS

### PR DESCRIPTION
**Pull request by as-com**
This is based off of WordPress.com's Terms of Service.

### CODE REVIEW

**Comment by Radical-from-Scratch** [comment]
I'll have to make some tweaks but I am Ok with it!

**Comment by Jonathan50** [comment]
@Radical-from-Scratch Why did you make a branch called `revert-32-as-com-tos`? ಠ_ಠ

**Comment by Radical-from-Scratch** [comment]
Because I was trying to merge it myself but BJ ninja'd me and I hit the wrong button.

**Comment by Jonathan50** [comment]
...wha? ^^

**Comment by as-com** [comment]
LOL, I was having fun with the restore/delete buttons.

**Comment by Jonathan50** [comment]
xD

**Comment by Radical-from-Scratch** [comment]
You were saying?

**Comment by Jonathan50** [comment]
That's enough.

**Comment by bjskistad** [comment]
Wow.

**Comment by Radical-from-Scratch** [comment]
It's actually kind of fun.

**Comment by Jonathan50** [comment]
Let's stop for real now. Seriously.

**Comment by Radical-from-Scratch** [comment]
You can't be the last person!

**Comment by Radical-from-Scratch** [comment]
There, now let's stop

**Comment by Jonathan50** [comment]
Does it matter who is the last person?

**Comment by Radical-from-Scratch** [comment]
Yes

**Pull request merged**
