### PR TITLE
Update server.js

### PR DESCRIPTION
**Pull request by joker314**
Strarting to add funuctionality for  other languages, but we need to collect their language preferences first.

### CODE REVIEW

**Comment by joker314** [comment]
This just allocates things to memory, and does not affect the appearance or security of the site. Because of this, I will merge 1800 Zulu time (approx. 1 hour) unless there is some objection

**Comment by joker314** [comment]
To prepare for the merge, I am posting the original here:
As a reminder, I will merge in 14 minutes, 1800 UTC, (not the time in the Uk btw, we are in BST)
[server.txt](https://github.com/Newawe/newawe/files/222278/server.txt)

**Comment by joker314** [comment]
Merged

**Comment by Radical-from-Scratch** [comment]
Except in special cases, you're not allowed to merge your own pull.

**Comment by joker314** [comment]
Why does the thing delete and restore 10 times? Also, sorry for merging my own code, but if you want, you can restore it through the text file.

**Comment by Radical-from-Scratch** [comment]
It's alright, just please don't do it again. The delete-and-restore joke is an an-dev joke started by as-com.

**Comment by joker314** [comment]
I see, thanks.

**Pull request merged**
