### PR TITLE
Responsive Container

### PR DESCRIPTION
**Pull request by CosmicWebServices**
Not too much just saw a todo and fixed it!

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
@herohamp @RonSkons

**Comment by CosmicWebServices** [comment]
@Mrcomputer1 @as-com @Krett12

**Comment by RonSkons** [comment]
If you'll look at [our code](https://github.com/Newawe/newawe/blob/master/views/global.html#L52), we have some inline CSS which does this already. Before I merge, could you also remove the inline styling and instead implement it in style.css?

--Ron

**Comment by CosmicWebServices** [comment]
Sure!

**Comment by CosmicWebServices** [comment]
I will make a new pr!

**Comment by CosmicWebServices** [comment]
#52 @RonSkons

**Comment by joker314** [comment]
Well it certainly won't harm Newawe, but it would be good to see it in action. I will take  look at it later if nobody else does

**Pull request closed without merging**
