### PR TITLE
Fixed nav and README.md

### PR DESCRIPTION
**Pull request by robinp7720**
Fixed padding in the navbar logo and create a README.md

The README speciefies the styleguide PSR-2 (Change this if you want, we should just follow a style). I did this so all code is much more readable.

I also added terms for fixing bugs/adding features. This is to stop commit from breaking things in the future and to stop confusion about adding features/fixing bugs.

We should also setup code climate to monitor the style of the code

### CODE REVIEW

**Comment by skistaddy** [comment]
I'm not sure about this PR. It doesn't have the div containers anymore... That's how we get our CSS. Will that wreck it? I'm going to leave this on pending.

**Comment by robinp7720** [comment]
I removed the w3 schools css. That's just placeholder HTML anyways.

**Comment by robinp7720** [comment]
I changed that with a span tag and removed the h6 tag. The main change was removing the h6 tag which was inappropriately used. It's a semantic element. You can add a div around the span but it's unnecessary.

**Comment by robinp7720** [comment]
@bjskistad I believed I have fixed that issue now. I have also fixed semantics in the login page and created a new class: form-container

**Comment by skistaddy** [comment]
You're a collaborator now... So you can just edit. I'll merge it.

**Comment by robinp7720** [comment]
@bjskistad I believe you can review this PR again and merge it

**Comment by skistaddy** [comment]
Is this PR on the master branch?

**Comment by robinp7720** [comment]
Yes, it is

**Pull request merged**
