### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by joker314**

### CODE REVIEW

**Comment by Jonathan50** [comment]
The character range still isn't fixed.

**Comment by joker314** [comment]
I removed the ^ after the @, isn't that the problem?

**Comment by Jonathan50** [comment]
That was a problem too, but not the only problem.
```js
"^[0-9A-Za-z_-.]+@[0-9A-Za-z_-.]+(:[0-9]+)?$"
```
should be
```js
"^[0-9A-Za-z_.-]+@[0-9A-Za-z_.-]+(:[0-9]+)?$"
```

**Comment by bjskistad** [comment]
@joker314 Make a new commit with the things J50 said.

**Comment by joker314** [comment]
@jonathan50 is the only thing you want changed is the order of -. and .- why would that make a difference?

**Comment by joker314** [comment]
nvm , i looked it up, I was creating a range between _ and . (invalid)

**Pull request closed without merging**
