### PR TITLE
Update global.html

### PR DESCRIPTION
**Pull request by bjskistad**
This is adding Intercom for Customer Info.

### CODE REVIEW

**Comment by herohamp** [comment]
What is this?

**Comment by bjskistad** [comment]
It allows it to view info about people who visit Newawe.

**Comment by Radical-from-Scratch** [comment]
As in, country,, or , as in, home address?

**Comment by herohamp** [comment]
How do we use it?

**Comment by bjskistad** [comment]
https://www.intercom.io/customer-intelligence

**Comment by herohamp** [comment]
can I have the login info?

**Comment by Radical-from-Scratch** [comment]
Me too. Please send it to my email: radicalfromscratch@gmail.com

**Comment by bjskistad** [comment]
Lol idk what it is

**Comment by herohamp** [comment]
*facepalm*

**Comment by Jonathan50** [comment]
@herohamp did you mean \*facepalm\*?

**Comment by bjskistad** [comment]
Probably.

**Comment by Jonathan50** [comment]
Not that it matters...

**Comment by bjskistad** [comment]
Totally not...

**Comment by Radical-from-Scratch** [comment]
Asterisks turn into italics for whatever reason.

**Comment by herohamp** [comment]
yes i was mean *     facepalm *

**Comment by Jonathan50** [comment]
> Asterisks turn into italics for whatever reason.

Because GitHub uses Markdown...

Escape using backslashes (\\) like \*hi\*

**Pull request merged**
