### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by as-com**
whooops

### CODE REVIEW

**Comment by jeandrek** [comment]
Did you get permission first? (I do approve though. Now I can contribute without being sued :package:)

**Comment by as-com** [comment]
Well, there's barely any code anyway... :package:

**Comment by ghost** [comment]
I endorse this. Done.

**Comment by jeandrek** [comment]
@Radical-from-Scratch even though, you technically still need permission from **ALL** contributors. Else you could get sued :package:

**Comment by ghost** [comment]
Nope, it says in the readme you only need one.

**Comment by jeandrek** [comment]
> Nope, it says in the readme you only need one.

I'm not talking about merging PRs :facepalm:, I'm talking about putting the GPL on it. Because it's copyrighted by all contributors.

**Comment by adri326** [comment]
I accept this.

**Comment by skistaddy** [comment]
I do too.

**Comment by robinp7720** [comment]
I accept this too. Aslong as I can reuse my code of my own projects. <-- If you write code/programs for a company you loose all copyright for your creation. So I have to say this incase this does become a company

**Comment by jeandrek** [comment]
> I accept this too. Aslong as I can reuse my code of my own projects. <-- If you write code/programs for a company you loose all copyright for your creation. So I have to say this incase this does become a company

Of course, so long as you GPL it too. (You can use your changes in another program without GPL'ing it, but no changes made from now on by people other than you)

**Comment by robinp7720** [comment]
Right..

**Pull request merged**
