### PR TITLE
Migrate to Feathers/React

### PR DESCRIPTION
**Pull request by as-com**
This pull request will serve as a progress tracker and discussion center while I reimplement much of the site using Feathers and React.

TODOS:

- [ ] Delete everything
- [x] Scaffold Feathers + Webpack
- [x] Add routing, with code splitting
- [ ] Implement user login/logout pages
- [ ] Re-add pages
- [ ] Internationalization
- [x] Add CSS
- [ ] Enforce code style
- [ ] Unit tests?

### CODE REVIEW

**Comment by Jonathan50** [comment]
Neat.

**Comment by herohamp** [comment]
Wait so should I create a live version of this?

**Comment by as-com** [comment]
Nah, we're barely even getting started. Just play with it on your local machines for now.

**Comment by herohamp** [comment]
ok

**Comment by as-com** [comment]
The code is now in a useable state - clone, `npm install`, `npm start`, and have fun.

**Comment by Jonathan50** [comment]
Since people have commited some stuff since, now there's conflicts -- but I don't think that'll be a problem since you started sorta from scratch anyway

**Comment by scratchyone** [comment]
Also, although it needs a sql server, if you just want to test it, just have a simple script listen on the sql server port, and it will still work. It just won't be able to save or get data.

**Comment by scratchyone** [comment]
When I run it, it says "error: Route: / - next is not defined" on lin 61 of app.js

**Comment by as-com** [comment]
@scratchyone You need to wait for it to finish compiling the JavaScript bundle (in development mode).

**Comment by joker314** [comment]
I'm confused, is this a re-write of what we have got so far in another language?

**Comment by as-com** [comment]
@joker314 This is a rewrite using a different method to make development faster and more scalable, but it's still in JavaScript.

**Comment by HittmanA** [comment]
I have not heard of feathers or react. Could you give me a link to their homepage?

**Comment by as-com** [comment]
@HittmanA http://facebook.github.io/react/ http://feathersjs.com

**Comment by Radical-from-Scratch** [comment]
I do not develop. The main site so it is of littlenconcern to me but are you rewriting everything?

**Comment by as-com** [comment]
@Newawe/administrators @Newawe/developers Should we use MongoDB? It seems more convenient than MySQL.

**Comment by Mrcomputer1** [comment]
@as-com Why is RethinkDB more convenient than MySQL?

**Comment by bjskistad** [comment]
Yeah...

**Comment by as-com** [comment]
I think a NoSQL database like RethinkDB would be more convenient because it's much easier to "change" the table structure and add more fields than with Sequelize, and has fancy features like arrays.

**Comment by HittmanA** [comment]
MySQL has arrays to I believe. Also what makes it easier to change? I also already have a good handle on MySQL so it would be hard to transition.

**Comment by as-com** [comment]
@HittmanA Here's MongoDB's article about differences between SQL and NoSQL: https://www.mongodb.com/blog/post/thinking-documents-part-1?jmp=docs

RethinkDB is similar in concept to MongoDB, but better: http://www.rethinkdb.com/blog/mongodb-biased-comparison/

**Comment by joker314** [comment]
May I help? I know  a tad of PHP and SQL?

**Comment by as-com** [comment]
We aren't using PHP, and because it's cool (and more flexible and easier to
understand), we're considering a NoSQL database.

You might want to learn JavaScript (we're using ECMAScript 6) and React. If
you already know how to program in a C-like language, you won't have much
trouble at all.

**Comment by Radical-from-Scratch** [comment]
1) Actually, 2/3 of the website is in PHP, and 2/3 of the website will be using an SQL database.

2) If you don't wanna bother, you can always help on the forums/wiki in PHP and HTML.

**Comment by Radical-from-Scratch** [comment]
I left a reply on the website

**Comment by herohamp** [comment]
We should use nodeBB and not fluxBB

**Comment by Radical-from-Scratch** [comment]
We already talked about this, and we are not.

**Comment by as-com** [comment]
Additionally, I noticed that you forked FluxBB and your hacking on the
core. I don't feel very well about that in terms of security. When FluxBB
publishes a new release, you might have trouble merging the changes in and
your forums may be compromised.

**Comment by Radical-from-Scratch** [comment]
Thank you for calmly voicing your concern. Keep in mind that just because FluxBB makes a new version doesn't mean it's bad for security to have the old one. However, I might just merge them in by hand.

**Comment by Radical-from-Scratch** [comment]
*Also, what do you suggest that I do instead?

**Comment by as-com** [comment]
You should probably write plugins for FluxBB that achieve the same
functionality that your writing directly into core. If FluxBB's plugin
system cannot do what you're trying to do, I suggest you try a different
forum software that is more extensible.

**Comment by Radical-from-Scratch** [comment]
Problem is, I don't know how to write a plugin. Honestly, while I understand your concern, this is no more dangerous than not upgrading FluxBB when a new version comes out.

**Comment by as-com** [comment]
Actually, in FluxBB language, they are called modifications. You may be
able to find resources here: http://fluxbb.org/resources/mods/

As a website owner who is very attentive to security, I have observed
thousands of bots probing for vulnerabilities. Not upgrading FluxBB after a
security release could spell disaster for the website, because when a
vulnerability is made public, it is only a matter of minutes before someone
starts scanning for and hijacking vulnerable websites. And no, I am not
exaggerating.

**Comment by HittmanA** [comment]
If he compromises the sites security then it is his fault and he is responsible.

**Comment by Radical-from-Scratch** [comment]
Actually, if the SITE'S security is compromised, it is 0% my fault, since I don't even work on the site. You mean the forums ;)

@as-com Fine, I'll look into some extensions.

**Comment by HittmanA** [comment]
@Radical-from-Scratch Ok yes you are correct. xD

**Comment by herohamp** [comment]
is this still worked on?

**Comment by as-com** [comment]
I decided that Newawe was not worth my time to work on.

**Comment by bjskistad** [comment]
I feel that Newawe has died. We don't have any funds to works with.

**Comment by Radical-from-Scratch** [comment]
Yeah, development has really gone down. I'm still watching, though. But I cannot help with the main site :(

**Comment by bjskistad** [comment]
Closed till further notice.

**Comment by Jonathan50** [comment]
> Yeah, development has really gone down. I'm still watching, though. But I cannot help with the main site :(

Why do you say that?

**Comment by Radical-from-Scratch** [comment]
Because I don't know any node, for literally the dozenth time.

**Pull request closed without merging**
