### PR TITLE
Make signup form color consistent (Make country selector white)

### PR DESCRIPTION
**Pull request by scratchyone**

### CODE REVIEW

**Comment by DrKat123** [comment]
Okay

**Comment by joker314** [comment]
I agree, it seemed a bit odd before.

**Comment by DrKat123** [comment]
I'll merge this

**Comment by bjskistad** [comment]
@scratchyone Would you like to join the Newawe team? We can invite you to the org and give you push access.

**Comment by scratchyone** [comment]
@bjskistad Sure! Thanks!

**Pull request merged**
