### PR TITLE
Prevent Newawe crashing

### PR DESCRIPTION
**Pull request by joker314**
This will catch exceptions, preventing the node js servers from crashing.

### CODE REVIEW

**Comment by herohamp** [comment]
Seems good +1 should I pull?

**Comment by Jonathan50** [comment]
But then it'll just exit, it won't continue serving!!

**Comment by joker314** [comment]
I'm a bit confused. Should the catch clause go before the listen bit, so that the next request will get processed, or am I confused?

**Comment by as-com** [comment]
Why are we still investing effort into this version? I recommend you guys help out with the feathers branch.

**Comment by bjskistad** [comment]
Ok. :)

**Pull request closed without merging**
