### PR TITLE
Login for Recaptcha

### PR DESCRIPTION
**Pull request by CosmicWebServices**

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
@herohamp

**Comment by JordanB-1337** [comment]
Hmm, I'm not sure that you should need to enter a CAPTCHA to log in, maybe just to register.

**Comment by CosmicWebServices** [comment]
Well it is more secure in a way

**Comment by JordanB-1337** [comment]
Yeah, but having to enter a CAPTCHA every single time you try to log in sounds annoying. Maybe after a few incorrect tries?

**Comment by CosmicWebServices** [comment]
I mean CAPTCHA is not that difficult

**Comment by CosmicWebServices** [comment]
I mean how many times can a person really log in

**Comment by JordanB-1337** [comment]
Alright, I mean it's not the end of the world.

**Comment by jeandrek** [comment]
Registering sort of proves they aren't a bot

**Comment by JordanB-1337** [comment]
Well I was thinking that it might be good against brute force bots, but on the _first_ try they are almost _guaranteed_ to be the right person.

**Comment by JordanB-1337** [comment]
btw jon https://s31.postimg.org/5yssm5fwb/2873645.png

**Comment by CosmicWebServices** [comment]
What if it is a bot trying to login to an existing account. It has happened

**Comment by JordanB-1337** [comment]
We're not gonna assume it's a bot on the _first_ try.

**Comment by CosmicWebServices** [comment]
Yeah true

**Pull request merged**
