### PR TITLE
Design overhaul

### PR DESCRIPTION
**Pull request by robinp7720**
Removed a lot of the broken css and fixed the design of the page.

### CODE REVIEW

**Comment by skistaddy** [comment]
I hope this works...

**Comment by robinp7720** [comment]
@bjskistad would it be possible if I could be given push access to the repo?

**Comment by skistaddy** [comment]
Yeah, just added you. :)

**Comment by robinp7720** [comment]
@bjskistad awesome, thanks!

**Comment by skistaddy** [comment]
:D

**Pull request merged**
