### PR TITLE
Proposition for an create.html

### PR DESCRIPTION
**Pull request by adri326**
Please do not accept without checking it.

It is my proposition to check if JS is enabled, if it is it'll show the editor that you guys wanted to create (I didn't created it) and if JS isn't enabled it'll show an non-JS solution.

### CODE REVIEW

**Comment by skistaddy** [comment]
Hmmm... I guess it's worth a shot.

**Comment by ghost** [comment]
Hey uhh why is this not closed

**Comment by ghost** [comment]
Baran, did I miss something? Are we using the old repo? Why is a bunch of stuff happening here?

**Comment by skistaddy** [comment]
No. I just wanted to resolve this.

**Comment by ghost** [comment]
Okay.

**Pull request merged**
