### PR TITLE
GH HTML Update

### PR DESCRIPTION
**Pull request by bjskistad**
Hey guys. I added a search bar in this PR. Check it out. :D

### CODE REVIEW

**Comment by herohamp** [comment]
Is it tested?

**Comment by herohamp** [comment]
+1 we need at least one more person to say +1 though to accept

**Comment by bjskistad** [comment]
K.

**Comment by herohamp** [comment]
Should we just accept it as  it changes almost nothing and I just tested it?

**Comment by bjskistad** [comment]
How does it look?

**Comment by herohamp** [comment]
decent here let me update the live to show you

**Comment by bjskistad** [comment]
K. Live link?

**Comment by herohamp** [comment]
http://newawelive.herohamp.xyz/

**Comment by herohamp** [comment]
Ok I updated the live to include the icon again. how do u like?

**Comment by herohamp** [comment]
I need to go! Bye

**Comment by bjskistad** [comment]
Looks good!

**Comment by adri326** [comment]
+1, it's okay, shall we use our own search algorithm or another one?

**Comment by Radical-from-Scratch** [comment]
We can program our own later, but for now I''ll see about setting up Google Custom Search.

**Comment by bjskistad** [comment]
I like that idea.

**Comment by Radical-from-Scratch** [comment]
Put the following code where-ever the search box should go.

`<script>
  (function() {
    var cx = '016025608616163530852:rsbtthvpyu8';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search>`

**Comment by Radical-from-Scratch** [comment]
Keep in mind that it's searching newawe.com so for now it will not show any results until we move.

**Comment by bjskistad** [comment]
Ok.

**Comment by Radical-from-Scratch** [comment]
Actually, AFAIK, the <script> part can go anywhere, it's just the `<gcse:search>` at the end you must be cautious about

**Comment by bjskistad** [comment]
Made a PR. Feel free to check it out, and edit it. :D

**Pull request merged**
