### PR TITLE
toUpperCase

### PR DESCRIPTION
**Pull request by joker314**
But it really depends on whether you prefer to write it as "newawe" or "Newawe"

### CODE REVIEW

**Comment by JordanB-1337** [comment]
Everyone writes "newawe" but it's really called "Newawe".

**Comment by JordanB-1337** [comment]
Also, you only need to make PRs for changing _code_, changing text is fine.

**Comment by joker314** [comment]
Ok, thanks! :D

**Comment by joker314** [comment]
@bjskistad grrr!

**Comment by JordanB-1337** [comment]
That's kind of a "thing" the devs do :P

**Comment by joker314** [comment]
Yeah I heard, but still, grr

**Comment by skistaddy** [comment]
:P

**Comment by joker314** [comment]
It's OK. :P

**Comment by jeandrek** [comment]
What's the downvote for?

**Comment by JordanB-1337** [comment]
It's not ok :P

**Comment by herohamp** [comment]
2 downvotes ;P

**Comment by skistaddy** [comment]
XD

**Comment by JordanB-1337** [comment]
Bjskistad please chekc your pm on gitter

**Comment by haylinmoore** [comment]
:)

**Comment by haylinmoore** [comment]
😄

**Comment by CosmicWebServices** [comment]
Can we stop posting here! Thanks!

**Pull request merged**
