### PR TITLE
Separated frontend from backend

### PR DESCRIPTION
**Pull request by robinp7720**
All php has been extracted from the pages. Pages are rendered using a basic templating engine. This will allow you/us to easily change the frontend without worrying about breaking the backend code.

Though, this will break the compaibilty with github pages but using github pages for a code sharing site was never going to work.

### CODE REVIEW

**Comment by adri326** [comment]
Ouch, there's a lot of changes and things I don't understand (+ before instructions)

Edit: oh, the + comes out from GitHub, alright

**Comment by robinp7720** [comment]
Its just classes, it makes it much easier to handle larger chunks of code and allows you to separate large portions of the code.

If you don't use this approach or one similar to this, this project will become impossible to manage.

I would recommend you to read up about Object Oriented Programming. It will save you a lot of time.

**Comment by adri326** [comment]
I know Object Oriented Programming, I do some Java, but classes in PHP is pretty destabilizing

**Comment by robinp7720** [comment]
What do you mean? 
Classes in PHP are pretty similar to classes in Java

What do you not understand?

**Comment by adri326** [comment]
I understand everything, no worries, it's just that I've always used PHP without classes, and I got so much problems with vars that aren't global when I started implementing any function on my own website that I just gave up

**Comment by robinp7720** [comment]
Global vars are a mess and you should avoid them. You can merge this PR if you want.
If you don't want to merge it I'd just like to know why

**Comment by adri326** [comment]
I'm not the owner of the repository, but I'll do this (hope bjskistad won't strangle me)

**Comment by robinp7720** [comment]
Awesome! :)

He won't strangle you :p.This will make it so you can work purely on the front end or on the backend. It also force people to use a better and more readable style in PHP.

**Comment by adri326** [comment]
http://adri326.comli.com/newawe/
(temporally hosting)
It won't work :(

**Comment by adri326** [comment]
Oh, the **DIR** means that we need to put the dir into it? (how nuts am I)

**Comment by adri326** [comment]
No, it's okay, it works now, I fixed it. Thanks, it works fine!

**Comment by skistaddy** [comment]
Lol. NOW I'M GONNA STRANGLE YOU!!! XD

**Pull request merged**
