### PR TITLE
Stable

### PR DESCRIPTION
**Pull request by skistaddy**

### CODE REVIEW

**Comment by jeandrek** [comment]
So are you not going to merge this? Should the branch be deleted?

**Comment by skistaddy** [comment]
I deleted the branch.

**Comment by jeandrek** [comment]
@Radical-from-Scratch why lock?

**Comment by ghost** [comment]
We have decided that we will not be merging it. There isn't much more to say.

**Comment by ghost** [comment]
But I guess I could unlock it :/

**Comment by ghost** [comment]
unlocked

**Comment by jeandrek** [comment]
I'm not saying you should unlock it, just wondering...

**Comment by ghost** [comment]
It doesn't really matter a lot, it just helps organize. Relocking.

**Pull request closed without merging**
