### PR TITLE
User accounts

### PR DESCRIPTION
**Pull request by robinp7720**

### CODE REVIEW

**Comment by ghost** [comment]
There seems to be some problems with conflicts.

**Comment by robinp7720** [comment]
Yes thats because I told you guys to base your commit of of users but you didn't.
Now i'm going to over write all of your commits

**Comment by robinp7720** [comment]
WHat are those changes supposed to be in index.php..
Please try and create elegant code that works. Not just code that works

**Comment by ghost** [comment]
Also, the code that I am migrating alredy has a home for database info. Which one should we use? Hmm...

**Comment by robinp7720** [comment]
I created all of this. People LOOK AT WHAT OTHER PEOPLE HAVE ALREADY DONE
Edit: this is annoying me, serisouly

**Comment by ghost** [comment]
Yes, you should look at what other people have done >:(

**Comment by robinp7720** [comment]
@Radical-from-Scratch I was doing this for the past 3 days. I told everyone in the gitter chat to wait until I'm done

**Comment by ghost** [comment]
That's not really how GitHub works. You need to merge them in yourself, not overwrite everything and make someone else do it.

**Comment by robinp7720** [comment]
@Radical-from-Scratch I know, but every file has been changed, ltteraly. Most of the features added by all your commits were delt with my branch with half the code.

And I impleneted that before everyone else did

**Comment by haylinmoore** [comment]
Ladies stop fighting.

**Comment by jeandrek** [comment]
> Yes thats because I told you guys to base your commit of of users but you didn't.
> Now i'm going to over write all of your commits

What are you talking about?

**Comment by jeandrek** [comment]
What does

> ALl commits to master before the
> 
> create of the users branch has been overwriten. Please notice my
> warnings before committing. Thank you

mean? Why?

**Comment by jeandrek** [comment]
828c352c507958c4068b186f7706e9960f3e0849

Noooooooooooooooooooooooo why on earth did you do that?????
@robinp7720 pls explain

**Comment by CosmicWebServices** [comment]
This is really good

**Comment by JordanB-1337** [comment]
What is really good?

**Pull request closed without merging**
