### PR TITLE
Fix #66

### LINKED ISSUE #66: Sign up makes no request (and the log in page throws an error)
Because the JavaScript for the sign up page and log in page are in the same file which is loaded on both.

### PR DESCRIPTION
**Pull request by jeandrek**
I think this fixes #66. Untested.

### CODE REVIEW

**Comment by HittmanA** [comment]
Taking a look...

**Comment by HittmanA** [comment]
Can we get rid of the save net neutrality widget. At least until later.

**Comment by jeandrek** [comment]
If you change it before merging this then it'll probably cause a conflict, so I think it would be best to do it after merging or deciding not to merge.

**Comment by HittmanA** [comment]
Ill merge and then change it. Do I need to make a pull request for it?

**Comment by jeandrek** [comment]
I don't know.

**Comment by HittmanA** [comment]
Oh never mind i guess just leave it ;P

**Comment by jeandrek** [comment]
The registration page still doesn't work, because the registration button doesn't have the id "register-button". Do I need to make a pull request for it? :P

**Comment by jeandrek** [comment]
I'm going to see what happens when I add a commit to this pull request...

**Comment by HittmanA** [comment]
I wouldn't make a pull request for something so tiny ;P

**Comment by jeandrek** [comment]
Nothing, apparently.

Okay, I'll just commit and push to master.

**Comment by HittmanA** [comment]
Oh ok

**Comment by jeandrek** [comment]
Done.

**Comment by skistaddy** [comment]
Still isn't working.... 💢

**Comment by jeandrek** [comment]
But #66 is fixed, the request is being fixed. Registration still doesn't work but that is a server-side problem now.

**Comment by skistaddy** [comment]
K.

**Pull request merged**
