### PR TITLE
404

### PR DESCRIPTION
**Pull request by haylinmoore**
I added a 404 page and when you type and invaild URL it takes you to the 404!

### CODE REVIEW

**Comment by ghost** [comment]
ninja'd

**Comment by haylinmoore** [comment]
So it was good?

**Comment by haylinmoore** [comment]
did someone with php knowledge look at the code?

**Comment by skistaddy** [comment]
ik enough php to get by. XD

**Comment by haylinmoore** [comment]
so do I. but like I wanted a good person

**Comment by HittmanA** [comment]
I am pretty good with php. I made a login/register and logout page, and that code editor I made was php. I'll take a look.

**Comment by haylinmoore** [comment]
what code editor?

**Comment by HittmanA** [comment]
A custom one i made. Features parenthesis quotation mark (single and double) bracket and brace autocomplete, ability to actually use tab to tab, and live preview.

**Comment by haylinmoore** [comment]
nice

**Comment by HittmanA** [comment]
Well if it matters I took a look at the file changes and it looks all good except for one issue.

**Pull request merged**
